# Generated by Django 3.0.5 on 2021-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Results',
        ),
    ]
