# Generated by Django 3.0.5 on 2021-05-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210503_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=3)),
                ('Ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Exams')),
            ],
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
